# Generated by Django 2.2.6 on 2019-10-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='valor_aluguel',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='valor do aluguel'),
        ),
    ]
